language: go

go:
  - 1.12.7
  - master

notifications:
  email: false

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)